[package]
name = "kramers-moyal"
version = "0.1.0"
authors = ["Richard Janis Goldschmidt <janis.beckert@gmail.com>"]

[dependencies]
if_chain = "0.1"
itertools = "0.5"
ndarray = "0.7"

[dependencies.streaming-iterator]
version= "0.1.2"
features = ["std"]
